graph TD
  Thunk <--> Val/Ref
  Val/Ref --> ToVal/Ref
  Val/Ref --> Book/Archive
  Thunk <--> Book/Archive
  Book/Archive --> BookBuilder
  Thunk --> Shifter
  Thunk --> EloC
  Thunk --> EloEval
  Shifter --> EloC
  EloEval --> Thunk
  EloEval <--> Val/Ref
  BookBuilder --> Eff.Book
  ToVal/RefDerivation --> BookBuilder
  ToVal/Ref --> ToVal/RefDerivation
  Book/Archive --> EloC
  Book/Archive --> EloEval
  Book/Archive --> EloRT
  BookBuilder --> Predef.Book
  Predef.Book --> Eff.Book
  EloC --> Predef.Book
  Eff.Book --> EloRT
  Book/Archive --> Craft/Discipline
  Craft/Discipline --> CraftBuilder
  Effect --> Craft/Discipline
  Eff.Book --> Craft/Discipline
  Craft/Discipline --> EloRT
  EloEval --> EloRT
  Thunk --> Effect
  Effect --> EloRT

